builds:
  - skip: true
checksum:
  name_template: '{{ .ProjectName }}_sha256_checksums.txt'
  algorithm: sha256
  extra_files:
  - glob: ./blazehttp
release:
  # Same as for github
  # Note: it can only be one: either github, gitlab or gitea
  github:
    owner: kingfs
    name: blazehttp

  draft: false