name: goreleaser

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean --release-notes=./release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
